"""Pass 2: taxonomy derivation.

ONE single LLM call over all pass-1 titles and abstracts. The model
proposes 8-15 corpus-derived topics (slug name, one-sentence scope,
paper count) and the result is written to a file. The human then edits
it by hand; after that edit the label set is CLOSED and pass 3 assigns
papers to it.

Usage:

    python -m extractor.pass2 [--db data/review.db] [--out data/taxonomy.md] [--model MODEL]

The --out file is written (or overwritten) with the taxonomy. The human
edits that file; pass 3 reads it as the closed label set. The format is
described at the top of the output file.
"""

import argparse
import os
import sys

from . import db as _db
from .openrouter import chat
from .run import DEFAULT_DB, DEFAULT_MODEL

_SYSTEM = """\
You are a corpus taxonomy builder for a PhD literature review. You will
receive the title and abstract of every paper in the corpus. Your task is
to derive 8 to 15 topics that together partition this specific corpus.

Rules:
- Topics must come from what is ACTUALLY in the corpus. Do not use a
  generic agricultural-ML taxonomy.
- Each topic gets: a short slug name (lowercase, underscores, no spaces),
  a one-sentence scope definition, and a count of papers assigned to it.
- PARTITION COUNTS: assign every paper to exactly one primary topic for
  counting purposes. Each paper is counted under exactly one topic — the
  one that best fits its primary contribution. The counts across all
  topics must sum to exactly the number of papers you were given.
- Do NOT attempt to anticipate multi-label secondary topics at this stage.
  Multi-label assignment is Pass 3's job. Pass 2 counts are partition
  counts only.
- 8 topics minimum, 15 maximum. If fewer than 8 capture the corpus, widen
  them. If more than 15 seem necessary, merge the most similar.
- Do not invent topics that no paper in the list would actually receive.

OUTPUT FORMAT (output ONLY this, no other text before or after):

# Corpus Taxonomy
<!-- Generated by pass 2. Edit topic names, scope sentences, and counts
     freely. The slug on each ## line is what pass 3 will use as the
     allowed value for topic_primary and topics_secondary; keep it
     lowercase with underscores. Do not add or remove the ## markers;
     they delimit topics. The label set is closed after your edit. -->

## slug_name_here
Scope: One-sentence scope definition that distinguishes this topic from
the others.
Count: N

## next_slug_name
Scope: ...
Count: N

(one ## block per topic, nothing else)
"""


def _build_user(rows):
    """Build the user message: numbered list of title + abstract."""
    parts = [
        "CORPUS: " + str(len(rows)) + " papers.\n",
        "For each paper the abstract_verbatim (ASCII) is supplied. If "
        "abstract_verbatim is absent the row shows '(no abstract)'.\n",
    ]
    for i, row in enumerate(rows, start=1):
        title = row["title"] or "(no title)"
        abstract = row["abstract_verbatim"] or "(no abstract)"
        parts.append(
            str(i) + ". TITLE: " + title + "\n"
            "   ABSTRACT: " + abstract
        )
    return "\n\n".join(parts)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Pass 2: taxonomy derivation.")
    parser.add_argument("--db", default=DEFAULT_DB)
    parser.add_argument("--out", default="data/taxonomy.md")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument(
        "--provider-ignore", dest="provider_ignore", nargs="+", default=None,
        metavar="SLUG",
    )
    parser.add_argument(
        "--provider-order", dest="provider_order", nargs="+", default=None,
        metavar="SLUG",
    )
    args = parser.parse_args(argv)

    if not os.environ.get("OPENROUTER_API_KEY"):
        print(
            "ERROR: OPENROUTER_API_KEY is not set.",
            file=sys.stderr,
        )
        return 2

    conn = _db.connect(args.db)
    rows = conn.execute(
        "SELECT title, abstract_verbatim FROM review "
        "WHERE needs_ocr IS NOT 1 "
        "ORDER BY filename"
    ).fetchall()
    conn.close()

    if not rows:
        print("ERROR: no pass-1 rows found in " + args.db, file=sys.stderr)
        return 1

    n = len(rows)
    print("Pass 2: " + str(n) + " papers from " + args.db)
    print("Model: " + args.model)
    print("Output: " + args.out)
    print("Building taxonomy (one LLM call)...", flush=True)

    user_msg = _build_user(rows)
    prompt_chars = len(_SYSTEM) + len(user_msg)
    print("Prompt chars: " + str(prompt_chars), flush=True)

    result = chat(
        model=args.model,
        system=_SYSTEM,
        user=user_msg,
        temperature=0.0,
        max_tokens=4000,
        provider_ignore=args.provider_ignore,
        provider_order=args.provider_order,
    )

    print(
        "Done. elapsed=%.1fs total_elapsed=%.1fs retries=%d provider=%s"
        % (result.elapsed, result.total_elapsed, result.retries,
           result.provider or ""),
        flush=True,
    )

    taxonomy = result.content.strip()

    out_path = args.out
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(taxonomy + "\n")

    print("\n" + "=" * 78)
    print(taxonomy)
    print("=" * 78)
    print("\nTaxonomy written to " + out_path)
    print("Edit it by hand. When done, run pass 3 to assign papers.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
